// <auto-generated />
namespace Cafe_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class CapNhatNhanVien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CapNhatNhanVien));
        
        string IMigrationMetadata.Id
        {
            get { return "201910150744269_CapNhatNhanVien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
