using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using System.Data.Entity;

namespace CafeManagement.GUI
{
    public partial class Chart : DevExpress.XtraEditors.XtraForm
    {
        public Chart()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            CafeManagement.Data.CaPheContext dbContext = new CafeManagement.Data.CaPheContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.HoaDons.Load();
            // This line of code is generated by Data Source Configuration Wizard
            chartControl1.DataSource = dbContext.HoaDons.Local.ToBindingList();
        }
    }
}